# Automated Threat Intelligence Configuration
#
# This file demonstrates the simple "light switch" approach to enabling
# automated threat intelligence feeds in the AuthFramework.

# Global automation switch - Turn on/off ALL automated feeds
auto_update_enabled: true

# How often to check for updates (in seconds)
update_interval_seconds: 3600 # 1 hour

# Directory to store downloaded feeds
feeds_directory: "./threat-feeds"

# HTTP timeout for downloads
download_timeout_seconds: 30

# Individual feed configurations - Simple on/off switches
feeds:
  # FREE FEEDS - No API keys required, just flip enabled: true/false

  tor_exits:
    enabled: true # 🟢 ON - Tor exit node detection
    feed_type: TorExitNodes
    url: "https://check.torproject.org/torbulkexitlist"
    filename: "tor-exits.txt"
    format: PlainText
    custom_interval_seconds: 3600

  spamhaus_drop:
    enabled: true # 🟢 ON - Spamhaus DROP list
    feed_type: MaliciousIPs
    url: "https://www.spamhaus.org/drop/drop.txt"
    filename: "spamhaus-drop.txt"
    format: PlainText
    custom_interval_seconds: 3600

  emergingthreats_compromised:
    enabled: false # 🔴 OFF - Emerging Threats compromised IPs
    feed_type: MaliciousIPs
    url: "https://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt"
    filename: "emerging-threats-ips.txt"
    format: PlainText
    custom_interval_seconds: 7200

  # PAID FEEDS - Require API keys/licenses, disabled by default

  virustotal_malicious:
    enabled: false # 🔴 OFF - Requires VIRUSTOTAL_API_KEY environment variable
    feed_type: MaliciousIPs
    url: "https://www.virustotal.com/api/v3/intelligence/hunting_notification_files"
    filename: "virustotal-malicious.json"
    format: Json
    custom_interval_seconds: 1800
    headers:
      X-Apikey: "${VIRUSTOTAL_API_KEY}" # Set via environment variable

  maxmind_proxy_detection:
    enabled: false # 🔴 OFF - Requires MAXMIND_LICENSE_KEY environment variable
    feed_type: VpnProxy
    url: "https://download.maxmind.com/app/geoip_download?edition_id=GeoIP2-Anonymous-IP&license_key=${MAXMIND_LICENSE_KEY}&suffix=tar.gz"
    filename: "maxmind-proxy-ranges.tar.gz"
    format: Csv
    custom_interval_seconds: 86400 # Daily updates

  # CUSTOM FEEDS - Add your own threat intelligence sources

  company_blacklist:
    enabled: false # 🔴 OFF - Your company's custom blacklist
    feed_type: !Custom "CompanyBlacklist"
    url: "https://internal.company.com/security/blacklist.txt"
    filename: "company-blacklist.txt"
    format: PlainText
    custom_interval_seconds: 1800
    headers:
      Authorization: "Bearer ${COMPANY_API_TOKEN}"
